In [1]:
import  os

import numpy as np
import pandas as pd


from create_df_larger import read_df_larger
df, dfc, all_homes, appliance_min, national_average = read_df_larger()

df = df.rename(columns={'house_num_rooms':'num_rooms',
                        'num_occupants':'total_occupants',
                        'difference_ratio_min_max':'ratio_difference_min_max'})
K_min, K_max = 1,6
F_min, F_max=1,8

from all_functions import *
from features_larger import *

In [2]:
appliance="hvac"
month=6
all_homes = df['%s_%d' %(appliance, month)].dropna().index

In [5]:
e = df.head(10)

In [13]:
e

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,0.035733,2.928117,13.662900,132.869888,242.395737,543.781433,761.394043,902.418823,610.035828,395.169098,...,1,1,0.474893,0.474893,0.294793,0.643408,0.174546,0.211272,0.229516,0.361959
59,839.664001,593.832336,363.180054,26.709435,77.613205,197.951508,457.950378,700.443054,244.340973,81.064682,...,1,1,0.676444,0.676444,0.257895,0.658875,0.239970,0.349908,0.371225,0.483440
94,0.000000,0.000350,0.000100,5.825350,19.836948,66.621819,126.121681,155.045364,92.979385,33.392750,...,1,1,0.632353,0.632353,0.005334,0.693725,0.327498,0.042454,0.040892,0.021921
101,0.156117,1.194283,14.917400,101.432083,191.965454,325.858032,462.708923,485.186005,350.491455,192.567566,...,1,1,0.497935,0.497935,0.059620,0.595846,0.111481,0.055280,0.087353,0.130070
222,3.534967,14.446183,73.483833,366.165070,478.951691,896.467285,1077.890137,1139.740479,887.044739,584.328979,...,1,1,0.628507,0.628507,0.973529,0.897096,0.735893,0.779294,0.759488,0.799077
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0.651221,0.651221,0.487992,0.609298,0.159926,0.451737,0.536100,0.667718
364,1.465917,0.913250,0.860567,118.981178,236.925064,535.010376,736.468933,850.080811,642.858459,378.799713,...,1,1,0.166810,0.166810,0.271579,0.488024,0.134256,0.171710,0.202784,0.325019
545,1.852667,1.657483,15.749134,202.448410,350.414551,778.204224,1065.381104,1120.907593,788.107544,375.303040,...,1,1,0.451076,0.451076,0.513645,0.651225,0.139781,0.185730,0.275034,0.461537
624,262.711365,132.780670,112.008072,0.000150,72.737854,191.232803,307.978149,389.598602,239.580887,22.099518,...,1,1,0.687563,0.687563,0.028073,0.592825,0.121842,0.108438,0.100761,0.127409
661,0.000617,0.000567,11.170450,108.608322,221.594315,648.794067,942.087769,1069.414429,756.477905,399.598877,...,1,1,0.483762,0.483762,0.351928,0.641696,0.133096,0.224071,0.234975,0.415699

In [15]:
e_max = e.max()

In [16]:
e_max

hvac_1                       839.664001
hvac_2                       593.832336
hvac_3                       363.180054
hvac_4                       366.165070
hvac_5                       478.951691
hvac_6                       896.467285
hvac_7                      1077.890137
hvac_8                      1139.740479
hvac_9                       887.044739
hvac_10                      584.328979
hvac_11                      119.922401
hvac_12                      263.928680
wm_1                           9.439983
wm_2                           9.208900
wm_3                           8.207233
wm_4                           7.579433
wm_5                           7.205417
wm_6                           8.585417
wm_7                           7.718650
wm_8                           4.330916
wm_9                           7.676733
wm_10                          3.941250
wm_11                          7.290750
wm_12                          4.953150
fridge_1                     106.738914
fridge_2                      54.959934
fridge_3                      51.830147
fridge_4                     292.664917
fridge_5                     409.984528
fridge_6                     366.417053
                               ...
dw_8                          16.194668
dw_9                          15.518050
dw_10                         15.124816
dw_11                         15.506833
dw_12                         14.997566
dr_1                          87.896500
dr_2                          69.019661
dr_3                          86.557571
dr_4                          78.100914
dr_5                          80.869202
dr_6                          66.051651
dr_7                          65.921234
dr_8                          74.049484
dr_9                          74.754150
dr_10                         64.209534
dr_11                         88.301018
dr_12                         95.984467
num_rooms                      0.714286
area                           0.935053
total_occupants                1.000000
md_available                   1.000000
full_agg_available             1.000000
ratio_min_max                  0.687563
ratio_difference_min_max       0.687563
variance                       0.973529
skew                           0.897096
kurtosis                       0.735893
p_25                           0.779294
p_50                           0.759488
p_75                           0.799077
dtype: float64

In [17]:
e_norm = e.div(e.max())

In [6]:
from nmf import nmf

In [23]:
A, Y = nmf(e_norm.fillna(-1).values, 1000)

Starting NMF decomposition with 1000 latent features and 100 iterations.
Iteration 1: fit residual 103.0098 total residual 110.3118
Iteration 5: fit residual 111.5744 total residual 58.7873
Iteration 10: fit residual 140.4821 total residual 146.729
Iteration 15: fit residual 148.647 total residual 103.3132
Iteration 20: fit residual 35.933 total residual 110.0588
Iteration 25: fit residual 57.7544 total residual 114.2267
Iteration 30: fit residual 63.0291 total residual 115.3112
Iteration 35: fit residual 62.7796 total residual 115.0874
Iteration 40: fit residual 67.0278 total residual 116.834
Iteration 45: fit residual 64.5966 total residual 111.777
Iteration 50: fit residual 689.3936 total residual 698.3705
Iteration 55: fit residual 692.0019 total residual 127.8577
Iteration 60: fit residual 75.8212 total residual 121.5765
Iteration 65: fit residual 35.9514 total residual 107.2088
Iteration 70: fit residual 37.8361 total residual 118.4054
Iteration 75: fit residual 73.1857 total residual 140.6728
Iteration 80: fit residual 74.8312 total residual 99.5646
Iteration 85: fit residual 695.1417 total residual 704.7301
Iteration 90: fit residual 695.7358 total residual 132.3398
Iteration 95: fit residual 69.9674 total residual 136.7745
Iteration 100: fit residual 70.5365 total residual 103.1086

In [24]:
pd.DataFrame(np.dot(A, Y), index=e.index)

,0,1,2,3,4,5,6,7,8,9,...,123,124,125,126,127,128,129,130,131,132
26,0.349691,0.349691,0.349720,0.365978,0.509461,0.610120,0.710137,0.795402,0.691199,0.679032,...,1.003878,1.003878,0.693407,0.693407,0.350122,0.720176,0.349830,0.349820,0.349897,0.455466
59,8.142751,8.142753,8.142774,8.143068,8.143093,8.143017,8.142967,8.142971,8.142965,8.143003,...,8.142925,8.142925,8.142868,8.142868,8.142764,8.142859,8.142777,8.142771,8.142768,8.142777
94,1.296994,1.296993,1.297030,1.297528,1.297910,1.297802,1.298033,1.298137,1.297916,1.297560,...,1.299420,1.299420,1.298312,1.298312,1.297256,1.298205,1.297114,1.297124,1.297183,1.297301
101,0.018644,0.012326,0.061589,0.208450,0.393661,0.364824,0.480287,0.481701,0.421172,0.280341,...,1.095895,1.095895,0.787553,0.787553,0.066975,0.713648,0.160705,0.079931,0.125233,0.178179
222,0.103588,0.103582,0.204041,0.978926,0.973769,1.005064,1.013056,1.016548,1.010918,1.010549,...,1.021934,1.021934,0.896731,0.896731,0.895305,1.005960,0.859300,0.753493,0.824413,0.978245
252,0.462645,0.462649,0.462699,0.464079,0.463760,0.463899,0.464148,0.464706,0.464782,0.463560,...,1.037850,1.037850,0.983610,0.983610,0.524126,0.863963,0.572851,0.579557,0.705504,0.838203
364,0.005161,0.005085,0.007071,0.374359,0.539492,0.613835,0.689815,0.748711,0.729077,0.657142,...,0.997983,0.997983,0.289157,0.289157,0.360058,0.549761,0.276439,0.324062,0.360921,0.436864
545,0.022480,0.022473,0.042090,0.552177,0.722909,0.860814,0.980577,0.976172,0.881153,0.637580,...,0.987365,0.987365,0.643478,0.643478,0.519891,0.715391,0.186610,0.233932,0.355536,0.569879
624,0.012349,0.009498,0.017841,0.020077,0.047262,0.085635,0.138407,0.175870,0.143450,0.020402,...,0.202400,0.202400,0.124901,0.124901,0.006239,0.120954,0.037678,0.026729,0.019942,0.023576
661,0.001909,0.001202,0.016391,0.143922,0.408438,0.702526,0.833694,0.901199,0.834455,0.665501,...,0.917341,0.917341,0.664891,0.664891,0.357996,0.676243,0.171852,0.282545,0.302282,0.509279

In [11]:
e

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,0.035733,2.928117,13.662900,132.869888,242.395737,543.781433,761.394043,902.418823,610.035828,395.169098,...,1,1,0.474893,0.474893,0.294793,0.643408,0.174546,0.211272,0.229516,0.361959
59,839.664001,593.832336,363.180054,26.709435,77.613205,197.951508,457.950378,700.443054,244.340973,81.064682,...,1,1,0.676444,0.676444,0.257895,0.658875,0.239970,0.349908,0.371225,0.483440
94,0.000000,0.000350,0.000100,5.825350,19.836948,66.621819,126.121681,155.045364,92.979385,33.392750,...,1,1,0.632353,0.632353,0.005334,0.693725,0.327498,0.042454,0.040892,0.021921
101,0.156117,1.194283,14.917400,101.432083,191.965454,325.858032,462.708923,485.186005,350.491455,192.567566,...,1,1,0.497935,0.497935,0.059620,0.595846,0.111481,0.055280,0.087353,0.130070
222,3.534967,14.446183,73.483833,366.165070,478.951691,896.467285,1077.890137,1139.740479,887.044739,584.328979,...,1,1,0.628507,0.628507,0.973529,0.897096,0.735893,0.779294,0.759488,0.799077
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0.651221,0.651221,0.487992,0.609298,0.159926,0.451737,0.536100,0.667718
364,1.465917,0.913250,0.860567,118.981178,236.925064,535.010376,736.468933,850.080811,642.858459,378.799713,...,1,1,0.166810,0.166810,0.271579,0.488024,0.134256,0.171710,0.202784,0.325019
545,1.852667,1.657483,15.749134,202.448410,350.414551,778.204224,1065.381104,1120.907593,788.107544,375.303040,...,1,1,0.451076,0.451076,0.513645,0.651225,0.139781,0.185730,0.275034,0.461537
624,262.711365,132.780670,112.008072,0.000150,72.737854,191.232803,307.978149,389.598602,239.580887,22.099518,...,1,1,0.687563,0.687563,0.028073,0.592825,0.121842,0.108438,0.100761,0.127409
661,0.000617,0.000567,11.170450,108.608322,221.594315,648.794067,942.087769,1069.414429,756.477905,399.598877,...,1,1,0.483762,0.483762,0.351928,0.641696,0.133096,0.224071,0.234975,0.415699

In [247]:
out_home = {}
for train_idx, test_idx in LeaveOneOut(len(all_homes)):
    print test_idx
    train_home = all_homes[train_idx]
    test_homes = all_homes[test_idx]
    ei=(df['%s_%d' %(appliance, month)].ix[train_home]-df['%s_%d' %(appliance, month)].ix[test_homes].values[0]).abs()
    
    out = {}
    for length in range(1, 3):
        for features in list(combinations(monthly_plus_static_features, length))[:]:
            features_list = list(features)
            w=(df.ix[train_home][features_list]-df.ix[test_homes][features_list].values[0]).T.apply(np.linalg.norm)
            ff = ei[w.sort_values().index]
            ff.index = range(len(ff))
            o.index = range(len(o))
            if len(features)==1:
                out[features[0]] = (ff-o).abs().mean()
            else:
                out[features] = (ff-o).abs().mean()
    out_home[test_homes.values[0]] = pd.Series(out)

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
[30]
[31]
[32]
[33]
[34]
[35]
[36]
[37]
[38]
[39]
[40]
[41]
[42]
[43]
[44]
[45]
[46]
[47]
[48]
[49]
[50]
[51]
[52]
[53]
[54]
[55]
[56]
[57]
[58]
[59]
[60]
[61]
[62]
[63]
[64]
[65]
[66]
[67]
[68]
[69]
[70]
[71]
[72]
[73]
[74]
[75]
[76]
[77]
[78]
[79]
[80]
[81]
[82]
[83]
[84]
[85]
[86]
[87]
[88]
[89]
[90]
[91]
[92]
[93]
[94]

In [249]:
pd.DataFrame(out_home).mean(axis=1).sort_values().head(10)

aggregate_6                    188.765756
(aggregate_5, aggregate_6)     190.358333
(aggregate_2, aggregate_6)     192.416535
(aggregate_6, aggregate_10)    192.599927
(aggregate_3, aggregate_6)     193.232469
(aggregate_4, aggregate_6)     193.982387
(aggregate_6, aggregate_11)    194.058474
(aggregate_6, aggregate_12)    194.063831
(aggregate_6, aggregate_7)     195.626797
(aggregate_6, aggregate_9)     197.891378
dtype: float64

In [251]:
feature=['aggregate_6']
from sklearn.neighbors import KNeighborsRegressor
out_home = {}
for train_idx, test_idx in LeaveOneOut(len(all_homes)):
    print test_idx
    train_home = all_homes[train_idx]
    test_homes = all_homes[test_idx]
    clf = KNeighborsRegressor()
    clf.fit(df.ix[train_home][feature], df.ix[t])

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
[30]
[31]
[32]
[33]
[34]
[35]
[36]
[37]
[38]
[39]
[40]
[41]
[42]
[43]
[44]
[45]
[46]
[47]
[48]
[49]
[50]
[51]
[52]
[53]
[54]
[55]
[56]
[57]
[58]
[59]
[60]
[61]
[62]
[63]
[64]
[65]
[66]
[67]
[68]
[69]
[70]
[71]
[72]
[73]
[74]
[75]
[76]
[77]
[78]
[79]
[80]
[81]
[82]
[83]
[84]
[85]
[86]
[87]
[88]
[89]
[90]
[91]
[92]
[93]
[94]

In [213]:
pd.DataFrame(out_home).mean(axis=1).sort_values().head(2).index.values

array([('aggregate_1', 'aggregate_8'), ('aggregate_6', 'kurtosis')], dtype=object)

In [186]:
test_homes
df.ix[9982][['hvac_7','aggregate_7']]

hvac_7         628.271118
aggregate_7      0.251234
Name: 9982, dtype: float64

In [202]:
(df.ix[all_homes][['aggregate_1','aggregate_8']]-df.ix[9982][['aggregate_1','aggregate_8']]).abs().sort_values().head(5).index

TypeError: sort_values() takes at least 2 arguments (1 given)

In [208]:
(df.ix[all_homes][['aggregate_1','aggregate_8']]-df.ix[9982][['aggregate_1','aggregate_8']]).abs().apply(np.linalg.norm, axis=1).sort_values().head(5)

9982    0.000000
3456    0.010331
6836    0.017056
1415    0.019615
946     0.022526
dtype: float64

In [193]:
df.ix[(df.ix[all_homes]['aggregate_7']-df.ix[9982]['aggregate_7']).abs().sort_values().head(5).index]['hvac_7']

9982    628.271118
8236    586.851929
9134    501.521515
5785    632.560059
1953    634.215454
Name: hvac_7, dtype: float64

In [210]:
df.ix[[9982, 8236, 9134, 5785, 1953]]['fridge_7']

9982    36.290382
8236    63.765266
9134    62.894669
5785          NaN
1953    53.956333
Name: fridge_7, dtype: float64

In [147]:
df.ix[test_homes][features_list]

      ratio_min_max  ratio_difference_min_max
9982       0.447911                  0.447911

In [149]:
pd.Series(out).sort_values()

(kurtosis, total_occupants)                    3.724478
(aggregate_11, total_occupants)                3.798301
(aggregate_1, total_occupants)                 3.803750
(aggregate_7, total_occupants)                 3.930525
(p_25, total_occupants)                        3.933094
(aggregate_12, total_occupants)                3.942631
(aggregate_4, total_occupants)                 3.965827
(skew, total_occupants)                        3.999880
(p_50, total_occupants)                        4.002019
(aggregate_10, total_occupants)                4.026756
(aggregate_2, total_occupants)                 4.066203
(aggregate_3, total_occupants)                 4.079794
(aggregate_9, total_occupants)                 4.104027
(aggregate_5, total_occupants)                 4.161829
total_occupants                                4.177250
(aggregate_6, total_occupants)                 4.199010
(p_75, total_occupants)                        4.284376
(aggregate_8, total_occupants)                 4.296439
kurtosis                                       4.304815
(total_occupants, ratio_difference_min_max)    4.340704
(total_occupants, ratio_min_max)               4.340704
(num_rooms, total_occupants)                   4.408546
(skew, kurtosis)                               4.591504
(aggregate_11, kurtosis)                       4.638137
skew                                           4.661686
(aggregate_10, kurtosis)                       4.767525
(aggregate_12, kurtosis)                       4.817959
(aggregate_7, kurtosis)                        4.848070
(aggregate_4, kurtosis)                        4.956143
(aggregate_3, kurtosis)                        4.961748
                                                 ...
(aggregate_2, aggregate_3)                     5.661889
(aggregate_3, aggregate_10)                    5.662645
(aggregate_1, aggregate_12)                    5.663427
(aggregate_2, aggregate_9)                     5.664488
(aggregate_2, aggregate_10)                    5.667409
aggregate_2                                    5.668506
(aggregate_2, area)                            5.669632
(aggregate_10, area)                           5.670002
(aggregate_3, aggregate_9)                     5.671280
(aggregate_12, area)                           5.672641
(aggregate_8, p_25)                            5.673601
(aggregate_1, aggregate_4)                     5.679750
(aggregate_9, aggregate_10)                    5.680591
(aggregate_4, area)                            5.685025
(aggregate_1, p_75)                            5.687054
(aggregate_5, aggregate_6)                     5.691171
(aggregate_1, area)                            5.691351
(aggregate_4, aggregate_10)                    5.693925
(aggregate_10, aggregate_12)                   5.696493
aggregate_1                                    5.697270
(aggregate_1, aggregate_6)                     5.707644
(aggregate_2, aggregate_8)                     5.719182
(aggregate_5, area)                            5.733839
(aggregate_1, aggregate_8)                     5.756352
(aggregate_1, aggregate_10)                    5.766711
(area, skew)                                   5.772420
(aggregate_1, aggregate_9)                     5.787636
area                                           5.894156
(area, ratio_min_max)                          5.949902
(area, ratio_difference_min_max)               5.949902
dtype: float64

In [88]:
pd.Series(out).sort_values()

aggregate_1                NaN
aggregate_10               NaN
aggregate_11               NaN
aggregate_12               NaN
aggregate_2                NaN
aggregate_3                NaN
aggregate_4                NaN
aggregate_5                NaN
aggregate_6                NaN
aggregate_7                NaN
aggregate_8                NaN
aggregate_9                NaN
area                       NaN
kurtosis                   NaN
num_rooms                  NaN
p_25                       NaN
p_50                       NaN
p_75                       NaN
ratio_difference_min_max   NaN
ratio_min_max              NaN
skew                       NaN
total_occupants            NaN
dtype: float64

In [123]:
ff

0      5.470673
1     50.430283
2    222.558788
3    236.555954
4    164.782532
Name: hvac_5, dtype: float64

28.709368896484374

In [126]:
o

0      5.470673
1     50.430283
2    164.782532
3    222.558788
4    236.555954
Name: hvac_5, dtype: float64

In [127]:
ff

0      5.470673
1     50.430283
2    222.558788
3    236.555954
4    164.782532
Name: hvac_5, dtype: float64

In [128]:
ff

0      5.470673
1     50.430283
2    222.558788
3    236.555954
4    164.782532
Name: hvac_5, dtype: float64

In [131]:
len(monthly_plus_static_features)

23

In [253]:
df.columns

Index([u'hvac_1', u'hvac_2', u'hvac_3', u'hvac_4', u'hvac_5', u'hvac_6',
       u'hvac_7', u'hvac_8', u'hvac_9', u'hvac_10',
       ...
       u'md_available', u'full_agg_available', u'ratio_min_max',
       u'ratio_difference_min_max', u'variance', u'skew', u'kurtosis', u'p_25',
       u'p_50', u'p_75'],
      dtype='object', length=133)

In [256]:
e = df.head(10)

In [257]:
e

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,0.035733,2.928117,13.662900,132.869888,242.395737,543.781433,761.394043,902.418823,610.035828,395.169098,...,1,1,0.474893,0.474893,0.294793,0.643408,0.174546,0.211272,0.229516,0.361959
59,839.664001,593.832336,363.180054,26.709435,77.613205,197.951508,457.950378,700.443054,244.340973,81.064682,...,1,1,0.676444,0.676444,0.257895,0.658875,0.239970,0.349908,0.371225,0.483440
94,0.000000,0.000350,0.000100,5.825350,19.836948,66.621819,126.121681,155.045364,92.979385,33.392750,...,1,1,0.632353,0.632353,0.005334,0.693725,0.327498,0.042454,0.040892,0.021921
101,0.156117,1.194283,14.917400,101.432083,191.965454,325.858032,462.708923,485.186005,350.491455,192.567566,...,1,1,0.497935,0.497935,0.059620,0.595846,0.111481,0.055280,0.087353,0.130070
222,3.534967,14.446183,73.483833,366.165070,478.951691,896.467285,1077.890137,1139.740479,887.044739,584.328979,...,1,1,0.628507,0.628507,0.973529,0.897096,0.735893,0.779294,0.759488,0.799077
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0.651221,0.651221,0.487992,0.609298,0.159926,0.451737,0.536100,0.667718
364,1.465917,0.913250,0.860567,118.981178,236.925064,535.010376,736.468933,850.080811,642.858459,378.799713,...,1,1,0.166810,0.166810,0.271579,0.488024,0.134256,0.171710,0.202784,0.325019
545,1.852667,1.657483,15.749134,202.448410,350.414551,778.204224,1065.381104,1120.907593,788.107544,375.303040,...,1,1,0.451076,0.451076,0.513645,0.651225,0.139781,0.185730,0.275034,0.461537
624,262.711365,132.780670,112.008072,0.000150,72.737854,191.232803,307.978149,389.598602,239.580887,22.099518,...,1,1,0.687563,0.687563,0.028073,0.592825,0.121842,0.108438,0.100761,0.127409
661,0.000617,0.000567,11.170450,108.608322,221.594315,648.794067,942.087769,1069.414429,756.477905,399.598877,...,1,1,0.483762,0.483762,0.351928,0.641696,0.133096,0.224071,0.234975,0.415699

In [265]:
import nimfa

In [266]:
import scipy.sparse as spr

In [267]:
V = spr.csr_matrix(e)

In [268]:
V

<10x133 sparse matrix of type '<type 'numpy.float64'>'
	with 1327 stored elements in Compressed Sparse Row format>

In [269]:
nmf = nimfa.Nmf(V, max_iter=200, rank=2, update='euclidean', objective='fro')

In [270]:
nmf

nmf

In [271]:
nmf_fit = nmf()

In [273]:
nmf_fit.basis

In [274]:
W = nmf_fit.basis()
print('Basis matrix:\n%s' % W.todense())

Basis matrix:
[[ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]
 [ nan  nan]]

In [275]:
H = nmf_fit.coef()
print('Mixture matrix:\n%s' % H.todense())

Mixture matrix:
[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
   nan  nan  nan  nan  nan  nan  nan]]

In [276]:
e.isnull()

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
94,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
101,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
222,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
252,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
364,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
545,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
624,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
661,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [284]:
V[5,0]

nan

In [283]:
from s

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,0.035733,2.928117,13.662900,132.869888,242.395737,543.781433,761.394043,902.418823,610.035828,395.169098,...,1,1,0.474893,0.474893,0.294793,0.643408,0.174546,0.211272,0.229516,0.361959
59,839.664001,593.832336,363.180054,26.709435,77.613205,197.951508,457.950378,700.443054,244.340973,81.064682,...,1,1,0.676444,0.676444,0.257895,0.658875,0.239970,0.349908,0.371225,0.483440
94,0.000000,0.000350,0.000100,5.825350,19.836948,66.621819,126.121681,155.045364,92.979385,33.392750,...,1,1,0.632353,0.632353,0.005334,0.693725,0.327498,0.042454,0.040892,0.021921
101,0.156117,1.194283,14.917400,101.432083,191.965454,325.858032,462.708923,485.186005,350.491455,192.567566,...,1,1,0.497935,0.497935,0.059620,0.595846,0.111481,0.055280,0.087353,0.130070
222,3.534967,14.446183,73.483833,366.165070,478.951691,896.467285,1077.890137,1139.740479,887.044739,584.328979,...,1,1,0.628507,0.628507,0.973529,0.897096,0.735893,0.779294,0.759488,0.799077
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0.651221,0.651221,0.487992,0.609298,0.159926,0.451737,0.536100,0.667718
364,1.465917,0.913250,0.860567,118.981178,236.925064,535.010376,736.468933,850.080811,642.858459,378.799713,...,1,1,0.166810,0.166810,0.271579,0.488024,0.134256,0.171710,0.202784,0.325019
545,1.852667,1.657483,15.749134,202.448410,350.414551,778.204224,1065.381104,1120.907593,788.107544,375.303040,...,1,1,0.451076,0.451076,0.513645,0.651225,0.139781,0.185730,0.275034,0.461537
624,262.711365,132.780670,112.008072,0.000150,72.737854,191.232803,307.978149,389.598602,239.580887,22.099518,...,1,1,0.687563,0.687563,0.028073,0.592825,0.121842,0.108438,0.100761,0.127409
661,0.000617,0.000567,11.170450,108.608322,221.594315,648.794067,942.087769,1069.414429,756.477905,399.598877,...,1,1,0.483762,0.483762,0.351928,0.641696,0.133096,0.224071,0.234975,0.415699

In [295]:
def matrix_factorization(R, P, Q, K, steps=50, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in xrange(steps):
        for i in xrange(len(R)):
            for j in xrange(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in xrange(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in xrange(len(R)):
            for j in xrange(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in xrange(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001:
            break
    return P, Q.T

In [296]:
R = e.fillna(0).values

In [297]:
N = len(R)
M = len(R[0])
K = 2

P = np.random.rand(N,K)
Q = np.random.rand(M,K)

nP, nQ = matrix_factorization(R, P, Q, K)

In [298]:
nR = np.dot(nP, nQ.T)

In [301]:
pd.DataFrame(nR, columns=e.columns, index=e.index).head()

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,71.580188,50.666867,50.808755,146.974860,241.853626,537.913823,739.919152,812.419971,568.323639,310.906330,...,0.875437,0.875441,0.436418,0.436419,0.396827,0.591459,0.247061,0.285572,0.303648,0.402126
59,835.563899,578.625071,360.688520,13.773095,77.129431,215.668282,491.503689,740.437291,285.853141,73.050693,...,1.172892,1.172898,0.808095,0.808099,0.209158,0.751365,0.206028,0.307962,0.329278,0.454374
94,-5.671774,-3.649878,2.589765,36.799632,59.005025,129.978845,173.244013,184.504105,135.676120,76.594778,...,0.188140,0.188141,0.087431,0.087432,0.094462,0.128279,0.056654,0.063497,0.067464,0.088823
101,26.082691,18.717019,23.135011,87.394813,142.729063,316.570631,431.579697,469.875841,333.314181,183.999240,...,0.498866,0.498868,0.244250,0.244251,0.232544,0.337858,0.143272,0.164217,0.174575,0.230829
222,-65.481956,-43.082861,12.776648,299.473207,478.909469,1053.906916,1400.006326,1485.994620,1098.701027,622.299803,...,1.505640,1.505646,0.693625,0.693627,0.764720,1.027703,0.456780,0.510179,0.542008,0.713122

In [302]:
e.head()

,hvac_1,hvac_2,hvac_3,hvac_4,hvac_5,hvac_6,hvac_7,hvac_8,hvac_9,hvac_10,...,md_available,full_agg_available,ratio_min_max,ratio_difference_min_max,variance,skew,kurtosis,p_25,p_50,p_75
26,0.035733,2.928117,13.662900,132.869888,242.395737,543.781433,761.394043,902.418823,610.035828,395.169098,...,1,1,0.474893,0.474893,0.294793,0.643408,0.174546,0.211272,0.229516,0.361959
59,839.664001,593.832336,363.180054,26.709435,77.613205,197.951508,457.950378,700.443054,244.340973,81.064682,...,1,1,0.676444,0.676444,0.257895,0.658875,0.239970,0.349908,0.371225,0.483440
94,0.000000,0.000350,0.000100,5.825350,19.836948,66.621819,126.121681,155.045364,92.979385,33.392750,...,1,1,0.632353,0.632353,0.005334,0.693725,0.327498,0.042454,0.040892,0.021921
101,0.156117,1.194283,14.917400,101.432083,191.965454,325.858032,462.708923,485.186005,350.491455,192.567566,...,1,1,0.497935,0.497935,0.059620,0.595846,0.111481,0.055280,0.087353,0.130070
222,3.534967,14.446183,73.483833,366.165070,478.951691,896.467285,1077.890137,1139.740479,887.044739,584.328979,...,1,1,0.628507,0.628507,0.973529,0.897096,0.735893,0.779294,0.759488,0.799077